import type { TaskGroup } from './types';

/** Все чеклисты: id задачи уникален глобально */
export const TASK_GROUPS: Record<string, TaskGroup> = {
  'done-foundation': {
    id: 'done-foundation',
    title: 'Фундамент в коде',
    subtitle: 'Уже в репозитории — не откатывать',
    tasks: [
      { id: 'f-auth', label: 'Auth Supabase + профиль (displayName, avatar, profileId)', done: true, owner: 'tech' },
      { id: 'f-rating', label: 'Рейтинг привязан к profileId, не к имени', done: true, owner: 'tech' },
      { id: 'f-online-sb', label: 'Онлайн: createRoom, join, sync game_state', done: true, owner: 'tech' },
      { id: 'f-bank', label: 'Банковый режим: settlement_mode, buy_in, finish_game RPC', done: true, owner: 'tech' },
      { id: 'f-flags', label: 'productFlags + .env.example (CC, зал, Cash Arena)', done: true, owner: 'product' },
      { id: 'f-cc-db', label: 'Миграции wallets / ledger / tournaments (scaffold)', done: true, owner: 'tech' },
      { id: 'f-hall-code', label: 'OnlineHallScreen + listPublicWaitingRooms', done: true, owner: 'tech' },
      { id: 'f-settlement-ui', label: 'GameOverModal + prize_pool в онлайн-банке', done: true, owner: 'product' },
    ],
  },
  'mobile-polish': {
    id: 'mobile-polish',
    title: 'Мобильная полировка',
    subtitle: 'Чеклист перед массовым онбордином',
    tasks: [
      {
        id: 'mob-1',
        label: 'Пройти стол на 375×667: рука, сетка 2×2, козырь на колоде',
        owner: 'product',
        priority: 'high',
        eta: 'Q2',
        hint: 'docs/ЧТО-ДЕЛАТЬ-ДАЛЬШЕ-мобильная-позиционирование.md',
      },
      {
        id: 'mob-2',
        label: 'Google OAuth с телефона: auth-callback без чёрного экрана',
        owner: 'tech',
        priority: 'high',
        eta: 'Q2',
      },
      {
        id: 'mob-3',
        label: 'Supabase Redirect URLs: localhost + продакшен callback',
        owner: 'tech',
        priority: 'medium',
        eta: 'Q2',
      },
      {
        id: 'mob-4',
        label: 'Deal results modal: узкий экран без ReferenceError',
        owner: 'product',
        priority: 'high',
        eta: 'Q2',
        done: true,
      },
      {
        id: 'mob-5',
        label: 'APK smoke-test: cap sync + одна онлайн-партия',
        owner: 'tech',
        priority: 'medium',
        eta: 'Q3',
      },
    ],
  },
  'online-now': {
    id: 'online-now',
    title: 'Онлайн сейчас (Supabase)',
    subtitle: 'До переезда на WS — стабильность и egress',
    tasks: [
      {
        id: 'on-1',
        label: 'Включить PUBLIC_HALL на staging, smoke-test зала',
        owner: 'product',
        priority: 'medium',
        eta: 'Q2',
        hint: 'VITE_PUBLIC_HALL_ENABLED=true в .env.local',
      },
      {
        id: 'on-2',
        label: 'Замер egress: запросов/мин в waiting vs playing',
        owner: 'tech',
        priority: 'medium',
        eta: 'Q2',
        hint: 'docs/ONLINE-EGRESS-OPTIMIZATION-PLAN.md этап 1',
      },
      {
        id: 'on-3',
        label: 'Лёгкий poll: revision-only tick без полного JSON',
        owner: 'tech',
        priority: 'high',
        eta: 'Q2',
      },
      {
        id: 'on-4',
        label: 'Адаптивные интервалы poll + burst после своего хода',
        owner: 'tech',
        priority: 'medium',
        eta: 'Q2',
      },
      {
        id: 'on-5',
        label: 'Документировать runbook: absent host, maintenance tick',
        owner: 'tech',
        priority: 'low',
        eta: 'Q2',
      },
    ],
  },
  marketing: {
    id: 'marketing',
    title: 'Маркетинг (направление г)',
    subtitle: 'Параллельно с продуктом — без этого офлайн не окупится',
    tasks: [
      {
        id: 'm-1',
        label: 'One-liner + 3 буллета ценности (skill, не казино)',
        owner: 'product',
        priority: 'critical',
        eta: 'Q2',
      },
      {
        id: 'm-2',
        label: 'Контент-план 4 недели: 2 поста/нед + 1 видео/мес',
        owner: 'product',
        priority: 'high',
        eta: 'Q2',
      },
      {
        id: 'm-3',
        label: 'Лендинг / PWA: скриншоты стола, CTA «играть с друзьями»',
        owner: 'product',
        priority: 'high',
        eta: 'Q2',
      },
      {
        id: 'm-4',
        label: 'Канал комьюнити (TG/Discord): правила, модерация',
        owner: 'product',
        priority: 'medium',
        eta: 'Q2',
      },
      {
        id: 'm-5',
        label: '10 бета-тестеров: сценарий «создать комнату → 4 игрока»',
        owner: 'product',
        priority: 'high',
        eta: 'Q2',
        hint: 'Собрать feedback-форму на 5 вопросов',
      },
      {
        id: 'm-6',
        label: 'EN-версия ключевых текстов для международного партнёра',
        owner: 'intl',
        priority: 'medium',
        eta: 'Q3',
      },
      {
        id: 'm-7',
        label: 'Материалы для пилота Грузия: постер, QR на комнату',
        owner: 'product',
        priority: 'medium',
        eta: 'Q3',
      },
      {
        id: 'm-8',
        label: 'ASO черновик: название, описание, 5 скриншотов',
        owner: 'product',
        priority: 'medium',
        eta: 'Q4',
      },
    ],
  },
  'offline-ge': {
    id: 'offline-ge',
    title: 'Офлайн-якорь — Грузия (направление а)',
    subtitle: 'Легальный пилот через оператора с лицензией',
    tasks: [
      {
        id: 'ge-1',
        label: 'Список 3 gaming-lawyer контактов в Грузии',
        owner: 'product',
        priority: 'critical',
        eta: 'Q2',
      },
      {
        id: 'ge-2',
        label: 'Созвон юрист: стоимость, срок, формат партнёрства с клубом',
        owner: 'product',
        priority: 'critical',
        eta: 'Q2',
        hint: 'Зафиксировать ответ письменно (email)',
      },
      {
        id: 'ge-3',
        label: 'Shortlist 2–3 площадок / операторов с лицензией',
        owner: 'intl',
        priority: 'high',
        eta: 'Q2',
      },
      {
        id: 'ge-4',
        label: 'MOU / письмо о намерениях с выбранной площадкой',
        owner: 'intl',
        priority: 'high',
        eta: 'Q3',
      },
      {
        id: 'ge-5',
        label: 'Формат вечера: buy-in, призовая, бренд Up&Down на табло',
        owner: 'product',
        priority: 'high',
        eta: 'Q3',
      },
      {
        id: 'ge-6',
        label: 'QR в зале: скачать PWA + войти в комнату турнира',
        owner: 'tech',
        priority: 'medium',
        eta: 'Q3',
      },
      {
        id: 'ge-7',
        label: 'Пилот: 1 вечер, 8–16 игроков, фото/видео с согласия',
        owner: 'product',
        priority: 'high',
        eta: 'Q3',
      },
      {
        id: 'ge-8',
        label: 'Post-mortem пилота: P&L, повторять / масштабировать',
        owner: 'product',
        priority: 'medium',
        eta: 'Q3',
      },
    ],
  },
  'ws-server': {
    id: 'ws-server',
    title: 'WS — сервер (Node)',
    subtitle: 'Часть A · репозиторий server/ или отдельный репо',
    tasks: [
      {
        id: 'ws-a1',
        label: 'Инициализировать server/: package.json, tsconfig, npm run dev',
        owner: 'tech',
        priority: 'critical',
        eta: 'Нед. 1–2',
      },
      {
        id: 'ws-a2',
        label: 'WebSocket upgrade + heartbeat ping/pong',
        owner: 'tech',
        priority: 'critical',
        eta: 'Нед. 1–2',
      },
      {
        id: 'ws-a3',
        label: 'Протокол: create_room → код комнаты + roomId',
        owner: 'tech',
        priority: 'critical',
        eta: 'Нед. 2',
        hint: 'Документ server/PROTOCOL.md',
      },
      {
        id: 'ws-a4',
        label: 'Протокол: join_room, bid, play_card, state_sync',
        owner: 'tech',
        priority: 'critical',
        eta: 'Нед. 2–3',
      },
      {
        id: 'ws-a5',
        label: 'Валидация ходов: shared rules из src/game/',
        owner: 'tech',
        priority: 'critical',
        eta: 'Нед. 3',
      },
      {
        id: 'ws-a6',
        label: 'Комнаты в RAM: 3–4 слота, TTL 2ч без активности',
        owner: 'tech',
        priority: 'high',
        eta: 'Нед. 3',
      },
      {
        id: 'ws-a7',
        label: 'Reconnect: playerToken, grace 5 мин',
        owner: 'tech',
        priority: 'high',
        eta: 'Нед. 4',
      },
      {
        id: 'ws-a8',
        label: 'Dockerfile + GET /health → 200',
        owner: 'tech',
        priority: 'high',
        eta: 'Нед. 4',
      },
      {
        id: 'ws-a9',
        label: 'Деплой на VPS: Caddy TLS, wss:// URL владельцу',
        owner: 'tech',
        priority: 'critical',
        eta: 'Нед. 5–6',
        hint: 'docs/ONLINE-SERVER-INSTRUCTIONS.md',
      },
      {
        id: 'ws-a10',
        label: 'PM2/systemd + логирование + алерт при падении',
        owner: 'tech',
        priority: 'medium',
        eta: 'Нед. 6',
      },
    ],
  },
  'ws-client': {
    id: 'ws-client',
    title: 'WS — клиент (Up&Down app)',
    subtitle: 'Часть B · этот репозиторий',
    tasks: [
      {
        id: 'ws-b1',
        label: 'Добавить VITE_WS_URL в .env.example и Vercel',
        owner: 'product',
        priority: 'high',
        eta: 'Нед. 2',
      },
      {
        id: 'ws-b2',
        label: 'Создать lib/onlineWs.ts: connect, send, onMessage',
        owner: 'tech',
        priority: 'critical',
        eta: 'Нед. 3',
      },
      {
        id: 'ws-b3',
        label: 'Флаг VITE_ONLINE_TRANSPORT=supabase|ws',
        owner: 'tech',
        priority: 'high',
        eta: 'Нед. 3',
      },
      {
        id: 'ws-b4',
        label: 'LobbyScreen: create/join через WS при transport=ws',
        owner: 'product',
        priority: 'critical',
        eta: 'Нед. 4',
      },
      {
        id: 'ws-b5',
        label: 'GameTable онлайн: state только из сокета',
        owner: 'product',
        priority: 'critical',
        eta: 'Нед. 5',
        hint: '4 игрока, 2 устройства — acceptance',
      },
      {
        id: 'ws-b6',
        label: 'После game-complete: один вызов finish_game + рейтинг',
        owner: 'tech',
        priority: 'high',
        eta: 'Нед. 5',
      },
      {
        id: 'ws-b7',
        label: 'Индикатор соединения + кнопка «Переподключиться»',
        owner: 'product',
        priority: 'medium',
        eta: 'Нед. 6',
      },
    ],
  },
  'ws-migrate': {
    id: 'ws-migrate',
    title: 'WS — миграция с Supabase poll',
    subtitle: 'Часть C · после стабильной партии',
    tasks: [
      {
        id: 'ws-c1',
        label: '7 дней без P0 багов на WS в beta-группе',
        owner: 'all',
        priority: 'critical',
        eta: 'Нед. 7',
      },
      {
        id: 'ws-c2',
        label: 'WS default для новых комнат',
        owner: 'tech',
        priority: 'high',
        eta: 'Нед. 7',
      },
      {
        id: 'ws-c3',
        label: 'Отключить ROOM_SYNC_POLL в режиме ws',
        owner: 'tech',
        priority: 'high',
        eta: 'Нед. 7',
      },
      {
        id: 'ws-c4',
        label: 'Сверить egress Supabase: снижение ≥50%',
        owner: 'tech',
        priority: 'medium',
        eta: 'Нед. 8',
      },
    ],
  },
  'iap-infra': {
    id: 'iap-infra',
    title: 'IAP — инфраструктура',
    subtitle: 'Часть B1 · без gambling-лицензии',
    tasks: [
      {
        id: 'iap-i1',
        label: 'Решение: RevenueCat vs нативные сторы + Stripe (1 стр.)',
        owner: 'product',
        priority: 'critical',
        eta: 'Q3',
        hint: 'Согласовать с международным партнёром entity',
      },
      {
        id: 'iap-i2',
        label: 'Таблица entitlements + purchases в Supabase',
        owner: 'tech',
        priority: 'critical',
        eta: 'Q3',
      },
      {
        id: 'iap-i3',
        label: 'Edge Function: webhook → обновить entitlement',
        owner: 'tech',
        priority: 'critical',
        eta: 'Q3',
      },
      {
        id: 'iap-i4',
        label: 'featureFlags: isPremium, ownedSkus из Supabase',
        owner: 'tech',
        priority: 'high',
        eta: 'Q3',
      },
      {
        id: 'iap-i5',
        label: 'Sandbox: тестовая покупка проходит end-to-end',
        owner: 'product',
        priority: 'critical',
        eta: 'Q3',
      },
    ],
  },
  'iap-shop': {
    id: 'iap-shop',
    title: 'IAP — магазин UI',
    subtitle: 'Часть B2',
    tasks: [
      {
        id: 'iap-s1',
        label: 'Экран ShopScreen: вкладки Косметика / Подписка / Разовые',
        owner: 'product',
        priority: 'high',
        eta: 'Q3',
      },
      {
        id: 'iap-s2',
        label: 'Тема карт v1: 2 рубашки + превью в CardView',
        owner: 'product',
        priority: 'high',
        eta: 'Q3',
      },
      {
        id: 'iap-s3',
        label: 'Подписка «Премиум»: цена, benefits, paywall',
        owner: 'product',
        priority: 'high',
        eta: 'Q3',
      },
      {
        id: 'iap-s4',
        label: 'Кнопка «Восстановить покупки» (iOS/Android)',
        owner: 'product',
        priority: 'medium',
        eta: 'Q3',
      },
      {
        id: 'iap-s5',
        label: 'Бейдж Premium в профиле / лобби',
        owner: 'product',
        priority: 'low',
        eta: 'Q4',
      },
    ],
  },
  'iap-features': {
    id: 'iap-features',
    title: 'IAP — фичи за покупку',
    subtitle: 'Часть B3',
    tasks: [
      {
        id: 'iap-f1',
        label: 'Гейт isPersonalAiReplacementEnabled → entitlement',
        owner: 'tech',
        priority: 'high',
        eta: 'Q3',
      },
      {
        id: 'iap-f2',
        label: 'Режим 3 игрока: engine + UI офлайн',
        owner: 'product',
        priority: 'high',
        eta: 'Q4',
      },
      {
        id: 'iap-f3',
        label: '3 игрока в онлайн (слоты WS)',
        owner: 'tech',
        priority: 'medium',
        eta: 'Q4',
      },
      {
        id: 'iap-f4',
        label: 'SKU «3 игрока» — разовая покупка',
        owner: 'product',
        priority: 'medium',
        eta: 'Q4',
        hint: 'После MVP режима',
      },
    ],
  },
  'cc-core': {
    id: 'cc-core',
    title: 'CC — ядро (ledger)',
    subtitle: 'Часть C1 · миграции уже в БД',
    tasks: [
      {
        id: 'cc-1',
        label: 'VITE_CC_LEDGER_ENABLED=true на staging',
        owner: 'tech',
        priority: 'high',
        eta: 'Q3',
      },
      {
        id: 'cc-2',
        label: 'CcWalletBadge: balance + held в лобби',
        owner: 'product',
        priority: 'high',
        eta: 'Q3',
      },
      {
        id: 'cc-3',
        label: 'Кнопка «Ежедневный бонус» → claimCcDailyGrant',
        owner: 'product',
        priority: 'medium',
        eta: 'Q3',
      },
      {
        id: 'cc-4',
        label: 'Комната с CC buy-in: holdCcForRoom перед стартом',
        owner: 'tech',
        priority: 'high',
        eta: 'Q3',
      },
      {
        id: 'cc-5',
        label: 'Settle CC после finish_game',
        owner: 'tech',
        priority: 'high',
        eta: 'Q3',
      },
      {
        id: 'cc-6',
        label: 'ToS CC опубликованы (без cash-out)',
        owner: 'legal',
        priority: 'high',
        eta: 'Q3',
        hint: 'docs/TERMS-CC-DRAFT.md',
      },
      {
        id: 'cc-7',
        label: 'GEO_RU_CC_ONLY: скрыть Cash Arena в UI',
        owner: 'tech',
        priority: 'medium',
        eta: 'Q3',
        done: true,
      },
    ],
  },
  'cc-tournaments': {
    id: 'cc-tournaments',
    title: 'CC — турниры и пакеты',
    subtitle: 'Часть C2–C3',
    tasks: [
      {
        id: 'cc-t1',
        label: 'Пакеты CC как consumable IAP',
        owner: 'product',
        priority: 'medium',
        eta: 'Q4',
      },
      {
        id: 'cc-t2',
        label: 'Age gate 18+ на экранах CC',
        owner: 'product',
        priority: 'high',
        eta: 'Q4',
      },
      {
        id: 'cc-t3',
        label: 'VITE_CC_TOURNAMENTS_ENABLED + список в лобби',
        owner: 'tech',
        priority: 'medium',
        eta: 'Q4',
      },
      {
        id: 'cc-t4',
        label: 'Регистрация sit-n-go + flow до старта',
        owner: 'product',
        priority: 'medium',
        eta: 'Q4',
      },
    ],
  },
  'beta-release': {
    id: 'beta-release',
    title: 'Gate: бета monetization',
    subtitle: 'Все пункты — перед публичным запуском IAP/CC',
    tasks: [
      {
        id: 'beta-1',
        label: 'WS: 4 игрока, 30 мин без desync',
        owner: 'all',
        priority: 'critical',
        eta: 'Q3',
      },
      {
        id: 'beta-2',
        label: 'Sandbox IAP: подписка или тема куплена',
        owner: 'product',
        priority: 'critical',
        eta: 'Q3',
      },
      {
        id: 'beta-3',
        label: 'Entitlement виден на втором устройстве того же аккаунта',
        owner: 'tech',
        priority: 'high',
        eta: 'Q3',
      },
      {
        id: 'beta-4',
        label: 'CC: daily grant + комната hold/settle на staging',
        owner: 'tech',
        priority: 'high',
        eta: 'Q4',
      },
      {
        id: 'beta-5',
        label: 'CASH_ARENA_ENABLED=false в проде',
        owner: 'tech',
        priority: 'critical',
        eta: 'всегда',
        done: true,
      },
      {
        id: 'beta-6',
        label: 'Privacy + ToS ссылаются на CC без cash-out',
        owner: 'legal',
        priority: 'high',
        eta: 'Q4',
      },
    ],
  },
  'phase2-entity': {
    id: 'phase2-entity',
    title: 'Волна 2 — entity и PSP',
    tasks: [
      {
        id: 'p2-e1',
        label: 'Dashboard метрик: DAU, D1/D7, IAP conversion',
        owner: 'product',
        priority: 'high',
        eta: 'Q4+',
      },
      {
        id: 'p2-e2',
        label: 'Выбор юрисдикции entity (не РФ mass-market)',
        owner: 'intl',
        priority: 'critical',
        eta: 'Q4+',
      },
      {
        id: 'p2-e3',
        label: 'PSP shortlist + compliance questionnaire',
        owner: 'intl',
        priority: 'high',
        eta: 'Q4+',
      },
      {
        id: 'p2-e4',
        label: 'Lawyer sign-off до включения Cash Arena UI',
        owner: 'legal',
        priority: 'critical',
        eta: 'Q4+',
      },
    ],
  },
  'phase2-license': {
    id: 'phase2-license',
    title: 'Волна 2 — лицензии online cash',
    tasks: [
      {
        id: 'p2-l1',
        label: 'Whitelist стран (документ 1 стр.)',
        owner: 'legal',
        priority: 'critical',
        eta: 'Q4+',
      },
      {
        id: 'p2-l2',
        label: 'KYC провайдер выбран',
        owner: 'intl',
        priority: 'high',
        eta: 'Q4+',
      },
      {
        id: 'p2-l3',
        label: 'Geo-block + age gate в Cash Arena',
        owner: 'tech',
        priority: 'high',
        eta: 'Q4+',
      },
    ],
  },
};
